# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8081:8080

  web:
    build: .
    container_name: php_web
    links:
      - db
    depends_on:
      - db
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
